global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: [http://docker.for.mac.localhost:8090/actuator/health]
        labels:
          name: 'exchange'
      - targets: [http://docker.for.mac.localhost:8092/actuator/health]
        labels:
          name: 'balance'
      - targets: [http://docker.for.mac.localhost:8093/actuator/health]
        labels:
          name: 'matching'
      - targets: [http://docker.for.mac.localhost:8094/actuator/health]
        labels:
          name: 'settle'
      - targets: [http://docker.for.mac.localhost:8095/actuator/health]
        labels:
          name: 'persistor'
      - targets: [http://docker.for.mac.localhost:8096/actuator/health]
        labels:
          name: 'user'
      - targets: [http://docker.for.mac.localhost:8099/actuator/health]
        labels:
          name: 'data'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: docker.for.mac.localhost:9115 # Blackbox exporter.

  - job_name: 'exchange-api-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8090']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8096']

  - job_name: 'balance-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8092']

  - job_name: 'matching-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8093']

  - job_name: 'settle-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8094']

  - job_name: 'kafka-persistor'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8095']

  - job_name: 'data-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.localhost:8099']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
